function readme_callback(src,event)
    str=['粘度计使用操作须知：',char(13,10)','1, Ctrl+N 创建新文件。按 inplace 键, 锥板转子归位；',char(13,10)',...
        '2, 点击 RX 读取静止状态下读数，然后将该数值输入Initial_value栏；',char(13,10)',...
        '3, Speed 栏输入转速，先按 rotate 旋转，然后按RX键开始采集数据；',char(13,10)',...
        '4, Viscosity栏出现示数后，等待Variance栏相对稳定后RX off, 点击Save；',char(13,10)',...
        '5, 调整电机运动时请关闭RX(Up, down速度请勿过高)。 '];
    h_msg=msgbox(str,'Readme');
    %ht = findobj(h_msg, 'Type', 'text');
    %set(ht, 'FontSize', 10, 'Unit', 'normal');
    set(h_msg,'Color',[1 1 1]); 
    %movegui(h_msg,'center');
end